### ISSUE TITLE
2.0 Todo list

### ISSUE THREAD

**Issue by mouse0w0** [UnknownStudio/UDPLib#20]
API：
- [X] ASM + Anno Command
- [ ] Rewrite Conversation API
- [ ] Particle Utils
- [ ] Tab
- [ ] Hologram
- [ ] Ground item
- [ ] Database
- [ ] Player data API

Nms：
- [ ] NMS Entity AI
- [ ] NMS Network API
- [ ] NMS Fake Entity (Fake Item)

Features：
- [ ] Simple 'Help' command implement
- [ ] TabComplete trie tree lib
- [ ] Dependency inject
- [ ] Modularization

Tools:
- [ ] Developer Kit
- [ ] In-game Test Kit
- [ ] NBT Editor

 Deprecated：
- ~Structured Text API~
- ~Safe Op Command~
- ~ASMEventBus injector~
